models/alert.py
import uuid
from typing import Dict
from models.item import Item
from models.model import Model


class Alert(Model):
    collection = "alerts"

    def __init__(self, item_id: str, price_limit: float, _id: str = None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.item_id = item_id
        self.item = Item.find_by_id(item_id)
        self.price_limit = price_limit
        self._id = _id or uuid.uuid4.hex

    def json(self) -> Dict:
        return{
            "_id" : self._id,
            "price_limit" : self.price_limit,
            "item_id" : self.item_id
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_price_reached(self):
        if self.item.price < self.price_limit:
            print(f"{self.item} has reached a price under {self.price_limit}. Latest price: {self.item.price}")

models/item.py
import re
import uuid
from typing import Dict
import requests
# type hinting - means we give params the expected var type,
# it wont break the program, only pops up warning
from bs4 import BeautifulSoup
from models.model import Model


class Item(Model):
    collection = 'items'  # mongo collection in which it will be kept

    def __init__(self, url: str, tag_name: str, query: Dict, _id: str = None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.url = ""
        self.tag_name = tag_name
        self.query = query
        self.price = None
        self._id = _id or uuid.uuid4.hex

    def __repr__(self):
        return f"<Item {self.url}>"

    #type hinting for return value of function is with an arrow at the declaration
    def load_price(self) -> float:
        response = requests.get(self.url)
        content = response.content
        soup = BeautifulSoup(content, "html.parser")
        element = soup.find(self.tag_name, self.query)
        string_price = element.text.strip()
        pattern = re.compile(r"(\d+,?\d*\.\d*)")
        match = pattern.search(string_price)
        found_price = match.group(1)
        without_comma = found_price.replace(",", "")
        self.price = float(without_comma)
        return self.price

    def json(self) -> Dict:
        return{
            "_id" : self._id,
            "url" : self.url,
            "tag_name" : self.tag_name,
            "query" : self.query
        }


models/model.py
from abc import ABCMeta, abstractmethod
from typing import List, TypeVar, Type, Dict

from common.database import Database

T = TypeVar('T', bound='Model')


class Model(metaclass=ABCMeta):
    # this way we force child classes to implemented the property collection
    # we don't give it value, cause if we would and then forget to implement it in child classes
    # data would be kept in the collection define here which is a bug
    collection: str
    _id: str

    def __init__(self, *args, **kwargs):
        pass

    #The definitions about of collection and init is just to get rid of the errors.
    # it does nothing and has to be overridden in the child class

    @abstractmethod
    def json(self) -> Dict:
        raise NotImplementedError

#now you can create a class that extends Model,
# if you won't implelment json method inside youll get an error
    @classmethod
    def all(cls: Type[T]) -> List[T]:
        elements_from_db = Database.find(cls.collection, {})
        # if we would return just the items_from_db it will return a list like object.
        # instead we use cls to create an item object for each items that returns from the cursor
        return [cls(**elem) for elem in elements_from_db]

    def save_to_mongo(self):
        # the update method will insert new doc to the db
        # unless there is already a record with the relevant id
        # in this case it will update the row
        Database.update(self.collection, {"_id": self._id}, self.json())

    def remove_from_mongo(self):
        Database.remove(self.collection, {"_id": self._id})

    @classmethod
    def find_one_by(cls: Type[T], attribute: str, value: str) -> T:
        return cls(**Database.find_one(cls.collection, {attribute: value}))

    @classmethod
    def find_many_by(cls: Type[T], attribute: str, value:str) -> List[T]:
        return [cls(**elem) for elem in Database.find(cls.collection, {attribute: value})]

    @classmethod
    def find_by_id(cls: Type[T], _id: str) -> T:
        return cls.find_one_by("_id", _id)

app.py
from flask import Flask, render_template

from views.items import item_blueprint
from views.alerts import alert_blueprint

app = Flask(__name__)
app.register_blueprint(item_blueprint, url_prefix='/items')
app.register_blueprint(alert_blueprint, url_prefix='/alerts')


@app.route('/')
def home():
    return render_template('home.html')


if __name__ == '__main__ ':
    app.run(port=4996,debug=True)

views/alerts.py
import json
from flask import request, render_template, Blueprint
from models.alert import Alert

alert_blueprint = Blueprint('alerts', __name__)

@alert_blueprint.route('/')
def index():
    alerts = Alert.all()
    return render_template('alerts/index.html', alerts=alerts)


@alert_blueprint.route('/new', methods=['GET', 'POST'])
def new_alert():
    if request.method == 'POST':
        item_id = request.form['item_id']
        price_limit = request.form['price_limit']
        Alert(item_id, price_limit).save_to_mongo()
    return render_template('alerts/new_alert.html')

views/items.py
import json
from flask import request, render_template, Blueprint
from models.item import Item

item_blueprint = Blueprint('items', __name__)


@item_blueprint.route('/')
def index():
    items = Item.all()
    return render_template('items/index.html', items=items)


@item_blueprint.route('/new', methods=['GET', 'POST'])
def new_item():
    if request.method == 'POST':
        query = json.loads(request.form['query'])
        Item(request.form['url'], request.form['tag_name'], query).save_to_mongo()

    return render_template('items/new_item.html')

templates/alerts/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1>Alerts</h1>
</header>
<sction>
    <div class="list-group mb-3">
        {% for alert in {{ alerts }} %}
            <div class="list-group-item">
                <h4>Alert</h4>
                <p>
                    <a href="{{alert.item.url}}">{{alert.item.url}}</a>
                </p>
            </div>
        {% endfor %}
    </div>
    <!-- usage of url_for is part of flask but can be used with jinja
     it takes blueprint name (items), then a function inside(new_item) -->
    <a class="btn btn-primary" href="{{ url_for('alerts.new_alert') }}">Create New</a>
</sction>

{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content %}
    <header>
        <h1>Create Alert</h1>
    </header>
    <section class="create-item-form">
        <form method="post">
          <div class="form-group">
            <label for="item_id">Item ID</label>
            <input type="text" class="form-control" id="item_id" name="item_id">
          </div>
          <div class="form-group">
            <label for="price_limit">Price Limit</label>
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="120" aria-describedby="priceLimitHelp">
            <small id="priceLimitHelp" class="form-text text-muted">The price limit for which you'd like to get alert for, in the same currency of the website </small>
          </div>
          <button type="submit" class="btn btn-primary">Create Alert</button>
        </form>
    </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Price Alerts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

templates/items/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1>Items</h1>
</header>
<sction>
    <div class="list-group mb-3">
        {% for item in {{ items }} %}
            <div class="list-group-item">
                <h4>Item</h4>
                <p>
                    <a href="{{item.url}}">{{item.url}}</a>
                </p>
            </div>
        {% endfor %}
    </div>
    <!-- usage of url_for is part of flask but can be used with jinja
     it takes blueprint name (items), then a function inside(new_item) -->
    <a class="btn btn-primary" href="{{ url_for('items.new_item') }}">Create New</a>
</sction>

{% endblock %}

templates/items/new_item.html
{% extends "base.html" %}

{% block content %}
    <header>
        <h1>Create Item</h1>
    </header>
    <section class="create-item-form">
        <form method="post">
          <div class="form-group">
            <label for="url">Item Url</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="https://...">
          </div>
          <div class="form-group">
            <label for="tag_name">Tag Name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" aria-describedby="tagNameHelp">
            <small id="tagNameHelp" class="form-text text-muted">What is the html tag of the element that contains the item price?</small>
          </div>
          <div class="form-group">
            <label for="query">Query</label>
            <input type="text" class="form-control" id="query" name="query" placeholder="span" aria-describedby="queryHelp">
            <small id="queryHelp" class="form-text text-muted">Json query formatted as {"element_attribute":"attribute_value"} of the price element</small>
          </div>
          <button type="submit" class="btn btn-primary">Create Item</button>
        </form>
    </section>
{% endblock %}